const districtWardMap = {
    "North": [
        "MUKHERJEE NAGAR",
        "SANGAM PARK",
        "MODEL TOWN",
        "ROHINI",
        "SHALIMAR BAGH SOUTH",
        "ROHINI CENTRAL",
        "BEGUMPUR",
        "RANA PRATAP BAGH",
        "BAKHTAWAR PUR",
        "ALIPUR",
        "SAHIBABAD DAULAT PUR",
        "BANKNER",
        "BAWANA",
        "BHALSWA",
        "SAMAYPUR BADLI",
        "JAHANGIRPURI-I",
        "SARAI PIPAL THALA",
        "ADARASH  NAGAR",
        "DHIR PUR",
        "G.T.B. NAGAR",
        "ROHINI NORTH",
        "LIBAS PUR",
        "NARELA",
        "BHALASWA JAHAGIR PUR",
        "JAHANGIR PURI -II"
    ],
    "North East": [
        "GHONDA",
        "YAMUNA VIHAR",
        "JIWANPUR",
        "GOKALPUR",
        "SHIV VIHAR",
        "KARAWAL NAGAR EAST",
        "MUSTAFABAD",
        "KHAJOORI KHAS",
        "KARAWAL NAGAR WEST",
        "SONIA VIHAR",
        "BRAHAM PURI",
        "NEW USMANPUR",
        "BHAJANPURA",
        "NEHRU VIHAR",
        "TUKHMIR PUR"
    ],
    "West": [
        "KHYALA",
        "JANAK PURI NORTH",
        "JANAK PURI WEST",
        "JANAK PURI SOUTH",
        "PUNJABI BAGH",
        "NEW RANJIT NAGAR",
        "KIRTI NAGAR",
        "MANSAROWER GARDEN",
        "HASTSAL",
        "TILAK NAGAR",
        "MAJOR BHUPINDAR SINGH NAGAR",
        "VIKASPURI EAST",
        "MOHAN GARDEN",
        "NAWADA",
        "UTTAM NAGAR",
        "RANI BAGH",
        "PASCHIM VIHAR NORTH",
        "PASCHIM VIHAR SOUTH",
        "QUAMMRUDDIN NAGAR",
        "NANGLOI EAST",
        "PERAGHARHI",
        "GURU HARKISHAN NAGAR",
        "KARAM PURA",
        "EAST PATEL NAGAR",
        "WEST PATEL NAGAR",
        "RAJA GARDEN",
        "RAGHUBIR NAGAR",
        "RAJOURI GARDEN",
        "NANGAL RAYA",
        "SUBHASH NAGAR",
        "NANGLOI JAT WEST",
        "MADIPUR",
        "TAGORE GARDEN",
        "KUNWAR SINGH NAGAR",
        "VIKAS NAGAR",
        "VIKAS PURI",
        "MAHAVIR NAGAR",
        "BALJIT NAGAR",
        "NILOTHI",
        "VISHNU GARDEN"
    ],
    "East": [
        "GHONDLI",
        "ANARKALI",
        "MAYUR VIHAR PHASE-I",
        "DALLOPURA",
        "TRILOK PURI",
        "NEW ASHOK NAGAR",
        "KALYAN PURI",
        "KHICHRIPUR",
        "KONDLI",
        "GHAROLI",
        "VINOD NAGAR",
        "GEETA COLONY",
        "PREET VIHAR",
        "I.P EXTENTION",
        "SHAKARPUR",
        "LAXMI NAGAR",
        "MAYUR VIHAR PHASE II",
        "MANDAWALI",
        "PATPARGANJ",
        "PANDAV NAGAR",
        "KISHAN KUNJ"
    ],
    "South West": [
        "MILAP NAGAR",
        "SITA PURI",
        "CHHAWLA",
        "NANGLI SAKRAVATI",
        "KAKRAULA",
        "KHERA",
        "SADH NAGAR",
        "BINDAPUR",
        "DABRI",
        "MATIALA",
        "ROSHANPURA",
        "MAHAVIR ENCLAVE",
        "SAGARPUR WEST",
        "BIJWASAN",
        "MADHU VIHAR",
        "DICHAON KALAN",
        "PALAM",
        "MANGLAPURI",
        "NAJAFGARH"
    ],
    "Central": [
        "CHANDNI CHOWK",
        "MINTO ROAD",
        "KUCHA PANDIT",
        "BAZAR SITARAM",
        "IDGAH ROAD",
        "TURKMAN GATE",
        "BALLIMARAN",
        "RAM NAGAR",
        "QASABPURA",
        "PAHAR GANJ",
        "KAMLA NAGAR",
        "INDER LOK COLONY",
        "KISHAN GANJ",
        "DEPUTY GANJ",
        "KASHMERE GATE",
        "MAJNU KA TILA",
        "JAMA MASJID",
        "DEV NAGAR",
        "KAROL BAGH",
        "MODEL BASTI",
        "MALKAGANJ",
        "JHARODA",
        "MUKUND PUR",
        "TIMAR PUR",
        "RAJENDER NAGAR",
        "BURARI",
        "DARYAGANJ",
        "SHASTRI NAGAR"
    ],
    "New Delhi": [
        "DELHI CANTT CHARGE 1",
        "DELHI CANTT CHARGE 2",
        "DELHI CANTT CHARGE 4",
        "DELHI CANTT CHARGE 5",
        "DELHI CANTT CHARGE 6",
        "DELHI CANTT CHARGE 7",
        "DELHI CANTT CHARGE 8",
        "DELHI CANTT CHARGE 3",
        "NDMC CHARGE 1",
        "NDMC CHARGE 2",
        "NDMC CHARGE 3",
        "NDMC CHARGE 4",
        "NDMC CHARGE 5",
        "NDMC CHARGE 7",
        "NDMC CHARGE 8",
        "NDMC CHARGE 9",
        "VASANT VIHAR",
        "NANAK PURA",
        "VASANTKUNJ",
        "PUSA",
        "INDER PURI",
        "NARAINA",
        "SAGARPUR",
        "MAHIPALPUR",
        "KAPASHERA",
        "HARI NAGAR",
        "R. K. PURAM",
        "RAJ NAGAR"
    ],
    "South": [
        "MALVIYA NAGAR",
        "HAUZ RANI",
        "MUNIRKA",
        "DAKSHINPURI EXT.",
        "KHANPUR",
        "AMBEDKAR NAGAR",
        "MADANGIR",
        "PUSHP VIHAR",
        "SHAPUR JAT",
        "DEOLI",
        "CHHATARPUR",
        "AYA NAGAR",
        "BHATI",
        "KISHANGARH",
        "SAFDARJANG ENCLAVE",
        "HAUZ KHAS",
        "LADOSARAI",
        "SAID UL AJAIB",
        "SANGAM VIHAR",
        "MEHRAULI",
        "SANGAM VIHAR WEST",
        "TIGRI"
    ],
    "Shahdara": [
        "DILSHAD GARDEN",
        "NEW SEEMA PURI",
        "NAND NAGRI",
        "SUNDER NAGARI",
        "DURGA PURI",
        "ASHOK NAGAR",
        "RAM NAGAR",
        "WELCOME COLONY",
        "CHAUHAN BANGER",
        "ZAFFRABAD",
        "MAUJPUR",
        "SUBHASH MOHALLA",
        "KARDAM PURI",
        "JANTA COLONY",
        "BABAR PUR",
        "SABOLI",
        "HARSH VIHAR",
        "GANDHI NAGAR",
        "AZAD NAGAR",
        "RAGHUBAR PURA",
        "SHAHDARA",
        "JHILMIL",
        "VIVEK VIHAR",
        "DILSHAD COLONY",
        "KRISHNA  NAGAR",
        "ANAND VIHAR",
        "VISHWASH NAGAR",
        "DHARAMPURA"
    ],
    "South East": [
        "NDMC CHARGE 6",
        "NIZAMUDDIN",
        "BHOGAL",
        "KASTURBA NAGAR",
        "AMAR COLONY",
        "ANDREWSGANJ",
        "TUGHLAKABAD EXTN",
        "SANGAM VIHAR CENTRAL",
        "SANGAM VIHAR EAST",
        "CHIRAG DELHI",
        "CHITRANJAN PARK",
        "GREATER KAILASH-I",
        "SRI NIWASPURI",
        "EAST OF KAILASH",
        "GOVIND PURI",
        "KALKAJI",
        "TUGHLAKABAD",
        "PUL PEHLAD",
        "TEKHAND",
        "HARKESH NAGAR",
        "JAITPUR",
        "MEETHEYPUR",
        "BADAR PUR",
        "MOLARBAND",
        "OKHLA",
        "MADANPUR KHADAR",
        "SARITA VIHAR",
        "LAJPAT NAGAR",
        "KOTLA MUBARAKPUR",
        "ZAKIR NAGAR"
    ],
    "North West": [
        "ASHOK VIHAR",
        "WAJIRPUR",
        "SAWAN PARK",
        "NIMRI COLONY",
        "SHAKUR PUR",
        "KOHAT ENCLAVE",
        "RAMPURA",
        "TRI NAGAR",
        "SARASWATI VIHAR",
        "SHALIMAR BAGH NORTH",
        "PITAMPUR NORTH",
        "PITAMPURA SOUTH",
        "NAHARPUR",
        "ROHINI EAST",
        "MANGOLPURI  WEST",
        "MANGOLPURI  EAST",
        "ROHINI SOUTH",
        "SULTANPURI  SOUTH",
        "SULTANPURI  EAST",
        "KIRARI SULEMAN NAGAR",
        "KARALA",
        "POOTH KALAN",
        "VIJAY VIHAR",
        "RITHALA",
        "MUNDAKA",
        "BUDH VIHAR",
        "NITHARI",
        "SULTANPUR MAJRA",
        "MOTI NAGAR",
        "MANGOLPURI",
        "MANGOL PURI  NORTH",
        "PRATAP VIHAR",
        "PREM NAGAR"
    ]
};